    1: import numpy as np
    2: import pytest
    3: 
    4: from pandas import CategoricalIndex
    5: import pandas._testing as tm
    6: 
    7: 
    8: class TestFillNA:
    9:     def test_fillna_categorical(self):
   10:         # GH#11343
   11:         idx = CategoricalIndex([1.0, np.nan, 3.0, 1.0], name="x")
   12:         # fill by value in categories
   13:         exp = CategoricalIndex([1.0, 1.0, 3.0, 1.0], name="x")
   14:         tm.assert_index_equal(idx.fillna(1.0), exp)
   15: 
   16:         cat = idx._data
   17: 
   18:         # fill by value not in categories raises TypeError on EA, casts on CI
   19:         msg = "Cannot setitem on a Categorical with a new category"
   20:         with pytest.raises(TypeError, match=msg):
   21:             cat.fillna(2.0)
   22: 
   23:         result = idx.fillna(2.0)
   24:         expected = idx.astype(object).fillna(2.0)
   25:         tm.assert_index_equal(result, expected)
   26: 
   27:     def test_fillna_copies_with_no_nas(self):
   28:         # Nothing to fill, should still get a copy for the Categorical method,
   29:         #  but OK to get a view on CategoricalIndex method
   30:         ci = CategoricalIndex([0, 1, 1])
   31:         result = ci.fillna(0)
   32:         assert result is not ci
   33:         assert tm.shares_memory(result, ci)
   34: 
   35:         # But at the EA level we always get a copy.
   36:         cat = ci._data
   37:         result = cat.fillna(0)
   38:         assert result._ndarray is not cat._ndarray
   39:         assert result._ndarray.base is None
   40:         assert not tm.shares_memory(result, cat)
   41: 
   42:     def test_fillna_validates_with_no_nas(self):
   43:         # We validate the fill value even if fillna is a no-op
   44:         ci = CategoricalIndex([2, 3, 3])
   45:         cat = ci._data
   46: 
   47:         msg = "Cannot setitem on a Categorical with a new category"
   48:         res = ci.fillna(False)
   49:         # nothing to fill, so we dont cast
   50:         tm.assert_index_equal(res, ci)
   51: 
   52:         # Same check directly on the Categorical
   53:         with pytest.raises(TypeError, match=msg):
   54:             cat.fillna(False)
